import type { Project, StatItem, TimelineEntry } from "@/models/types";

export const FALLBACK_PROJECTS: Project[] = [
  {
    slug: "cf-tracker",
    title: "CF Tracker",
    category: "cp",
    status: "live",
    year: 2026,
    type: "Personal project",
    metricValue: "300ms",
    metricLabel: "avg API response time",
    tags: ["Next.js", "Recharts", "MongoDB"],
    description:
      "Codeforces stat tracker with rating history charts and problem breakdowns.",
    featured: true,
    order: 0,
  },
  {
    slug: "taskflow",
    title: "TaskFlow",
    category: "web",
    status: "live",
    year: 2025,
    type: "Team project",
    metricValue: "200+",
    metricLabel: "active users",
    tags: ["TypeScript", "JWT", "Tailwind"],
    description: "Collaborative task management app with JWT auth and roles.",
    featured: true,
    order: 1,
  },
  {
    slug: "algoviz",
    title: "AlgoViz",
    category: "opensource",
    status: "live",
    year: 2025,
    type: "Open source",
    metricValue: "1.2k",
    metricLabel: "GitHub stars",
    tags: ["React", "Canvas API"],
    description: "Interactive algorithm visualizer for sorting and graph traversal.",
    featured: true,
    order: 2,
  },
  {
    slug: "dsa-notes",
    title: "DSA Notes",
    category: "cp",
    status: "live",
    year: 2024,
    type: "Personal project",
    metricValue: "80+",
    metricLabel: "topic write-ups",
    tags: ["Markdown", "Next.js"],
    description: "Searchable knowledge base of DSA patterns and editorial notes.",
    featured: true,
    order: 3,
  },
  {
    slug: "devboard",
    title: "DevBoard",
    category: "web",
    status: "live",
    year: 2024,
    type: "Personal project",
    metricValue: "99.9%",
    metricLabel: "uptime",
    tags: ["Next.js", "MongoDB", "Recharts"],
    description: "Analytics dashboard for tracking personal project metrics.",
    featured: true,
    order: 4,
  },
  {
    slug: "contest-notifier",
    title: "Contest Notifier",
    category: "opensource",
    status: "live",
    year: 2023,
    type: "Open source",
    metricValue: "40+",
    metricLabel: "forks",
    tags: ["Node.js", "Cron"],
    description: "CLI + Discord bot that pings upcoming CP contests.",
    featured: true,
    order: 5,
  },
];

export const FALLBACK_STATS: StatItem[] = [
  { key: "cf_rating", label: "Codeforces rating", value: "1847", order: 0 },
  { key: "problems", label: "Problems solved", value: "420+", order: 1 },
  { key: "contests", label: "Contests joined", value: "65", order: 2 },
  { key: "projects", label: "Projects shipped", value: "12", order: 3 },
];

export const FALLBACK_TIMELINE: TimelineEntry[] = [
  {
    role: "SCHOOL · FIRST LINES OF CODE",
    meta: "SELF-TAUGHT · 2022",
    heading: "Where it began",
    description:
      "Started with C and basic problem solving, got curious about how programs actually think.",
    order: 0,
  },
  {
    role: "CODEFORCES · COMPETITIVE PROGRAMMING",
    meta: "DSA FOUNDATIONS · 2023",
    heading: "Sharpening the fundamentals",
    description:
      "Began solving on Codeforces daily, built strong data structures and algorithms fundamentals through contests.",
    order: 1,
  },
  {
    role: "FULL-STACK · NEXT.JS & TYPESCRIPT",
    meta: "WEB DEVELOPMENT · 2024",
    heading: "Designing for the web",
    description:
      "Learned Next.js, TypeScript, Tailwind CSS and MongoDB, shipped my first full-stack web apps end to end.",
    order: 2,
  },
  {
    role: "BUILDING IN PUBLIC · FREELANCE",
    meta: "PERSONAL PROJECTS · 2025-26",
    heading: "Where I am now",
    description:
      "Actively competing in contests, taking on freelance and personal projects, and growing this portfolio.",
    order: 3,
  },
];
